sonar.projectKey=bayer-int_mother-ml_AYYm8s2yT0di1-yfiuDv
sonar.python.version=3.10,3.11,3.12, 3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=xunit-test.xml
sonar.exclusions = **/examples/**
sonar.coverage.exclusions=test/**,**/scripts/**
sonar.cpd.exclusions=docs/**,test/**,**/scripts/**

# Ignore issue (i)python:S117 (naming convention) on all files
sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=ipython:S117
sonar.issue.ignore.multicriteria.e1.resourceKey=**
sonar.issue.ignore.multicriteria.e2.ruleKey=python:S117
sonar.issue.ignore.multicriteria.e2.resourceKey=**
