name: Workflow for model testing and release

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.12"

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v6

      - name: Setup uv environment 📚
        id: setup-uv-env
        uses: ./.github/actions/setup-uv-env
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          install-args: "--extra report --extra rna --extra tabpfn"

      # - name: Run type checks #needs a lot of type fixing
      #   run: |
      #     uv run poe check-types
      - name: Run style checks
        run: |
          uv run poe check-style

      - name: Run linter
        run: |
          uv run poe check-lint
  test:
    needs: style
    runs-on: ubuntu-latest
    if: ${{ success() && (github.ref == 'refs/heads/main' || github.event_name ==
      'pull_request') }}
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13", "3.14" ]
      # When set to true, GitHub cancels all in-progress jobs if any matrix job fails.
      fail-fast: true
    name: Test 🧪 using 🐍
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v6
        # needed for report dependencies
      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1 libxrender1 libxtst6

      - name: Setup uv environment 📚
        id: setup-uv-env
        uses: ./.github/actions/setup-uv-env
        with:
          python-version: ${{ matrix.python-version }}
          install-args: "--extra rna --extra report --extra tabpfn --extra clustering
            --group test_duration"

      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      - name: Test and generate code coverage report
        run: |
          uv run poe coverage

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-py${{ matrix.python-version }}
          path: ./coverage.xml

      - name: Test mother without extra dependencies
        run: |
          uv sync --no-dev
          uv run poe dist-test

  test-slow:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ success() && (github.ref == 'refs/heads/main' || github.event_name ==
      'pull_request') }}
    name: Test Slow 🐢 using 🐍 3.12
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v6
        # needed for report dependencies
      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1 libxrender1 libxtst6

      - name: Setup uv environment 📚
        id: setup-uv-env
        uses: ./.github/actions/setup-uv-env
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          install-args: "--extra rna --extra report --extra tabpfn --extra clustering
            --group test_duration"

      - name: Download TabPFN checkpoint
        run: |
          uv run python examples/prepareTabpfn.py

      #----------------------------------------------
      #              run slow test suite
      #----------------------------------------------
      - name: Run slow tests
        run: |
          uv run poe test-slow

  release:
    name: Create Release package
    needs: test-slow
    if: success() && github.ref == 'refs/heads/main' &&
      !contains(github.event.head_commit.message, '[skip release]')
    runs-on: ubuntu-latest
    concurrency: release
    environment: release
    outputs:
      released: ${{ steps.release.outputs.released }}
      version: ${{ steps.release.outputs.version }}
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false # Make sure to not use the GITHUB_TOKEN for checkout and thus enable updating the version with the PAT
      - name: Set python version 🐍
        run: echo "PYTHON_VERSION=3.11" >> $GITHUB_ENV

      - name: Setup uv environment 📚
        id: setup-uv-env
        uses: ./.github/actions/setup-uv-env
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          install-args: "--extra report --extra rna --extra tabpfn"

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v10.2.0
        id: release
        with:
          github_token: ${{ secrets.PAT_RELEASE_PIPELINE }}

      #----------------------------------------------
      #              run publish
      #----------------------------------------------
      - name: Build package
        if: steps.release.outputs.released == 'true'
        shell: bash
        run: |
          uv build

      - name: Upload distribution artifacts
        if: steps.release.outputs.released == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish-pypi:
    name: Publish to PyPI
    needs: release
    if: needs.release.outputs.released == 'true'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download distribution artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

  build-mkdocs:
    name: Build MkDocs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1 libxrender1 libxtst6

      - name: Setup uv environment 📚
        id: setup-uv-env
        uses: ./.github/actions/setup-uv-env
        with:
          python-version: "3.11"
          install-args: "--group docs"

      - name: Build docs
        working-directory: mkdocs
        run: uv run mkdocs build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: mkdocs/site/

  deploy-mkdocs:
    name: Publish Docs
    needs: build-mkdocs
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    concurrency:
      group: github-pages
      cancel-in-progress: true
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
